### ISSUE TITLE
File Moving Seems to be Working Incorrectly

### ISSUE THREAD

**Issue by heatvent** [1337-server/automatic-ripping-machine#73]
### Description
When a rip is completed and HandBrake is exited, it looks like ARM tries to move to completed/extras and clean up files in raw/transcode several times.  I end up with either no movie in the completed directory or sometimes it is there and sometimes it ends up in extras for some reason.  It seems like there is something wrong with the logic or its missing quotations or something.

### Environment
Ubuntu 20.04
Latest git version

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
Can you share your log file ?

**Comment by heatvent** [comment]
I was chopping it down a bit ... here is an example of what is going on.  I deleted the multiple summary tables and labeled each attempt as Try 1, 2, etc.  In this example, the movie did get copied to the completed directory but here where the mutliple attempts to copy.  I will post another example of one that failed to move.

`[23-04-2021 21:09:55] DEBUG ARM: models.eject we unmounted disc/dev/sr0
[23-04-2021 21:09:55] DEBUG ARM: models.eject failed to eject/dev/sr0
[23-04-2021 21:09:55] DEBUG ARM: main.main New Title is Movie Title
[23-04-2021 21:09:55] INFO ARM: main.main Moving Movie /home/arm/media/transcode/movies/Movie Title/Movie Title.mkv to /home/arm/media/completed/movies/Movie Title (2008)
[23-04-2021 21:09:55] DEBUG ARM: utils.move_files Moving files:

TRY 1:

[23-04-2021 21:09:55] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/movies/Movie Title : /home/arm/media/transcode/movies/Movie Title/Movie Title.mkv : True : Movie Title (2008) : True
[23-04-2021 21:09:55] INFO ARM: utils.move_files Creating base title directory: /home/arm/media/completed/movies/Movie Title (2008)
[23-04-2021 21:09:55] INFO ARM: utils.move_files Track is the Main Title.  Moving '/home/arm/media/transcode/movies/Movie Title/Movie Title.mkv' to /home/arm/media/completed/movies/Movie Title (2008)
[23-04-2021 21:11:37] INFO ARM: main.main Moving Movie  to /home/arm/media/completed/movies/Movie Title (2008)
[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Moving files: 

TRY 2:

[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/movies/Movie Title :  : True : Movie Title (2008) : False
[23-04-2021 21:11:37] INFO ARM: utils.move_files Creating extras directory /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] INFO ARM: utils.move_files Moving '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] INFO ARM: main.main Moving Movie  to /home/arm/media/completed/movies/Movie Title (2008)
[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Moving files:

TRY 3:

[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/movies/Movie Title :  : True : Movie Title (2008) : False
[23-04-2021 21:11:37] INFO ARM: utils.move_files Moving '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] ERROR ARM: utils.move_files Unable to move '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] INFO ARM: main.main Moving Movie  to /home/arm/media/completed/movies/Movie Title (2008)
[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Moving files:

TRY 4:

[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/movies/Movie Title :  : True : Movie Title (2008) : False
[23-04-2021 21:11:37] INFO ARM: utils.move_files Moving '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] ERROR ARM: utils.move_files Unable to move '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] INFO ARM: main.main Moving Movie  to /home/arm/media/completed/movies/Movie Title (2008)
[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Moving files:

TRY 5:

[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/movies/Movie Title :  : True : Movie Title (2008) : False
[23-04-2021 21:11:37] INFO ARM: utils.move_files Moving '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] ERROR ARM: utils.move_files Unable to move '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] INFO ARM: main.main Moving Movie  to /home/arm/media/completed/movies/Movie Title (2008)
[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Moving files: 

TRY 6:

[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/movies/Movie Title :  : True : Movie Title (2008) : False
[23-04-2021 21:11:37] INFO ARM: utils.move_files Moving '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] ERROR ARM: utils.move_files Unable to move '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] INFO ARM: main.main Moving Movie  to /home/arm/media/completed/movies/Movie Title (2008)
[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Moving files: 

TRY 7:

[23-04-2021 21:11:37] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/movies/Movie Title :  : True : Movie Title (2008) : False
[23-04-2021 21:11:37] INFO ARM: utils.move_files Moving '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] ERROR ARM: utils.move_files Unable to move '' to /home/arm/media/completed/movies/Movie Title (2008)/extras
[23-04-2021 21:11:37] INFO ARM: main.main Removing raw path - /home/arm/media/raw/Movie Title
[23-04-2021 21:11:37] INFO ARM: main.main Removing raw path - /home/arm/media/transcode/movies/Movie Title
[23-04-2021 21:11:37] DEBUG ARM: main.main No raw files found to delete in /home/arm/media/transcode/movies/Movie Title - [Errno 2] No such file or directory: '/home/arm/media/transcode/movies/Movie Title'
[23-04-2021 21:11:37] INFO ARM: main.main Removing raw path - /home/arm/media/raw/Movie Title
[23-04-2021 21:11:37] DEBUG ARM: main.main No raw files found to delete in /home/arm/media/raw/Movie Title - [Errno 2] No such file or directory: '/home/arm/media/raw/Movie Title'
[23-04-2021 21:11:37] INFO ARM: main.main ARM processing complete`

**Comment by heatvent** [comment]
In this example the rip seemed to have ended up in the extras folder:

`Encode done!
HandBrake has exited.

[24-04-2021 03:29:45] INFO ARM: handbrake.handbrake_mainfeature Handbrake call successful
[24-04-2021 03:29:45] INFO ARM: handbrake.handbrake_mainfeature Handbrake processing complete
[24-04-2021 03:29:45] DEBUG ARM: handbrake.handbrake_mainfeature 


[24-04-2021 03:29:45] DEBUG ARM: models.eject we unmounted disc/dev/sr0
[24-04-2021 03:29:45] DEBUG ARM: models.eject failed to eject/dev/sr0
[24-04-2021 03:29:45] DEBUG ARM: main.main New Title is None
[24-04-2021 03:29:45] INFO ARM: main.main Moving Movie  to /home/arm/media/completed/movies/Movie Title
[24-04-2021 03:29:45] DEBUG ARM: utils.move_files Moving files:

Try 1:

[24-04-2021 03:29:45] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/movies/Movie Title :  : True : Movie Title : False
[24-04-2021 03:29:45] INFO ARM: utils.move_files Creating base title directory: /home/arm/media/completed/movies/Movie Title
[24-04-2021 03:29:45] INFO ARM: utils.move_files Creating extras directory /home/arm/media/completed/movies/Movie Title/extras
[24-04-2021 03:29:45] INFO ARM: utils.move_files Moving '' to /home/arm/media/completed/movies/Movie Title/extras
[24-04-2021 03:31:35] INFO ARM: main.main Moving Movie  to /home/arm/media/completed/movies/Movie Title
[24-04-2021 03:31:35] DEBUG ARM: utils.move_files Moving files: 

Try 2:

[24-04-2021 03:31:35] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/movies/Movie Title :  : True : Movie Title : False
[24-04-2021 03:31:35] INFO ARM: utils.move_files Moving '' to /home/arm/media/completed/movies/Movie Title/extras
[24-04-2021 03:31:35] ERROR ARM: utils.move_files Unable to move '' to /home/arm/media/completed/movies/Movie Title/extras
[24-04-2021 03:31:35] INFO ARM: main.main Moving Movie /home/arm/media/transcode/movies/Movie Title/Movie Title.mkv to /home/arm/media/completed/movies/Movie Title
[24-04-2021 03:31:35] DEBUG ARM: utils.move_files Moving files: 

Try 3:

[24-04-2021 03:31:35] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/movies/Movie Title : /home/arm/media/transcode/movies/Movie Title/Movie Title.mkv : True : Movie Title : True
[24-04-2021 03:31:35] INFO ARM: utils.move_files Track is the Main Title.  Moving '/home/arm/media/transcode/movies/Movie Title/Movie Title.mkv' to /home/arm/media/completed/movies/Movie Title
[24-04-2021 03:31:35] ERROR ARM: utils.move_files Unable to move '/home/arm/media/transcode/movies/Movie Title/Movie Title.mkv' to /home/arm/media/completed/movies/Movie Title - [Errno 2] No such file or directory: '/home/arm/media/transcode/movies/Movie Title/Movie Title.mkv'
[24-04-2021 03:31:35] INFO ARM: main.main Removing raw path - /home/arm/media/raw/Movie Title
[24-04-2021 03:31:35] INFO ARM: main.main Removing raw path - /home/arm/media/transcode/movies/Movie Title
[24-04-2021 03:31:35] DEBUG ARM: main.main No raw files found to delete in /home/arm/media/transcode/movies/Movie Title - [Errno 2] No such file or directory: '/home/arm/media/transcode/movies/Movie Title'
[24-04-2021 03:31:35] INFO ARM: main.main Removing raw path - /home/arm/media/raw/Movie Title
[24-04-2021 03:31:35] DEBUG ARM: main.main No raw files found to delete in /home/arm/media/raw/Movie Title - [Errno 2] No such file or directory: '/home/arm/media/raw/Movie Title'
[24-04-2021 03:31:35] INFO ARM: main.main ARM processing complete`

**Comment by 1337-server** [comment]
I can't seem to reproduce this, can you attach a full logfile.

**Comment by heatvent** [comment]
[MANHATTAN_EU.log](https://github.com/1337-server/automatic-ripping-machine/files/6372338/MANHATTAN_EU.log)

This is from the second example above ... the one where the video ended up in the extras directory.

**Comment by 1337-server** [comment]
Apologies for deleting your comment, but i just noticed that ARM doesn't safely deal with tmdb_api_key or ARM_API_KEY (everything else is fine)

I have already pushed a commit to fix this issue, ill keep trying to replicate the bugs you're experiencing. i will reply as soon as i have an update.

**Comment by 1337-server** [comment]
Can you test with the latest commit and see if the issue is resolved ? 

Thanks.

**Comment by heatvent** [comment]
Sorry was it the version from the 25th?  I have been using that version and
still have some files ending up in extras.  Also had a couple that didn’t
seem to save the completed file.  So still seems to have the issue.  I will
try updating again when I get a chance to see if you made any changes since
then.

**Comment by 1337-server** [comment]
No it was the version from today.

**Comment by heatvent** [comment]
Tried a couple of blu-ray discs and both ended up in the extras subfolder.  Attached is the debug log from one of them.

[log.txt](https://github.com/1337-server/automatic-ripping-machine/files/6410706/log.txt)

**Comment by heatvent** [comment]
Not sure if you had made additional edits to the scripts today but I just tried to pull down from gihub again and noticed main.py and another file were updated so I restarted and I am giving it another try to see if it is working.

**Comment by heatvent** [comment]
I tried a couple of discs and one ended up in the extras folder and the other seemed to work fine.  So I am seeing the same issue still.

FYI, I do have the completed folder mapped to a SMB share ... could that have something to do with it?  I guess I can give it a try with it unmounted and will see what happens.

**Comment by heatvent** [comment]
So I unmounted the share and retried.  I got the same result.  In the "extras" folder there is a folder with the same name / year as the title and then within that folder is the ripped file.  Strangely, the mkv file has the title but not the year in the name.

Maybe this has something to due with the length of the file name or use of special characters like "-" or "("?  Seems strange that ARM sometimes gets it right and other times not.

**Comment by 1337-server** [comment]
I think this may be caused by {ismainfeature} not being passed corrently to the utils.move_files function.

Can you check the job details page so either `/jobdetail?job_id=THE_JOB_ID` or visit the database page and find the correct job and click the poster image of the job.
Scroll to the bottom  and look for the tracks table (its at the very bottom)

Can you check that at least one of them is  both ripped=True and Main Feature=True


The job log does show that one of the tracks does get labelled as main feature, we just need to be sure that this track was added to the database.

`[01-05-2021 17:33:21] DEBUG ARM: utils.put_track Track #105 Length: 7832 fps: 23.976 aspect: 1.78 Mainfeature: True Source:  handbrake
[01-05-2021 17:33:21] DEBUG ARM: utils.put_track Track #112 Length: 41 fps: 23.976 aspect: 1.78 Mainfeature: False Source:  handbrake
[01-05-2021 17:33:22] DEBUG ARM: utils.put_track Track #113 Length: 7832 fps: 23.976 aspect: 1.78 Mainfeature: False Source:  handbrake`

**Comment by heatvent** [comment]
Yes, there is one track that is labeled as both Main Feature and Ripped. 

There are also some that are labeled as Main Feature False and Ripped True ... however, I don't end up with any extras.  Just the main movie in the extras folder.

**Comment by 1337-server** [comment]
Are there duplicates of the main track ? A track with the same size as the main feature but that shows as main feature =False ?

**Comment by heatvent** [comment]
Yes.  It is labeled main feature false and ripped true.

**Comment by 1337-server** [comment]
Ok, ill look into this now that its narrowed down it shouldn't be too long

**Comment by heatvent** [comment]
Thanks

**Comment by 1337-server** [comment]
Can you test the breakages branch ?

Ive added a fix to try and get around the problem, hopefully that solves this issue. if not let me know and ill keep working on it.

**Comment by heatvent** [comment]
Still experiencing the same issue ... the file ends up in the extras/movie_title (year)/ directory as movie_title.mkv (no year).  Just to make sure I used the breakages branch correctly (I don't use the git command much), I did the following to switch...

cd /opt/arm
sudo git fetch --all
sudo git checkout breakages
sudo git pull https://github.com/1337-server/automatic-ripping-machine

If I do "git branch" I see breakages in green with a ' next to it and v2_devel .. so it appear the breakages branch is currently selected.

Attached is the log file.
[log.txt](https://github.com/1337-server/automatic-ripping-machine/files/6446065/log.txt)

**Comment by 1337-server** [comment]
Yes that's the correct branch, thanks for testing anyway. Ill need to try and find another solution.

**Comment by mg-man** [comment]
Appreciate this issue is pretty old... but I am having issues with a few of the DVDs I've recently ripped -- which may be related.  In these specific cases, there is an error on the final move (to .../completed/movies) where the result is NOTHING gets moved, but EVERYTHING gets deleted!!  Very, very annoying... 

I'm currently using the v2_ubuntu18 branch, but suspect the underlying issue is present in the main branch(es) as well.

Here is the ultimate error from one of my logs...

[07-03-2022 05:39:28] INFO ARM: Moving Movie title_t01.mkv to /home/arm/media/completed/movies/Darkest Hour (2017)
[07-03-2022 05:39:28] INFO ARM: Track is the Main Title.  Moving 'title_**t01**.mkv' to /home/arm/media/completed/movies/Darkest Hour (2017)
[07-03-2022 05:39:28] ERROR ARM: Unable to move 'title_t01.mkv' to '/home/arm/media/completed/movies/Darkest Hour (2017)' - Error: [Errno 2] No such file or directory: '/home/arm/media/transcode/movies/Darkest Hour (2017)/title_t01.mkv'

If I scroll up in the log to where the (Handbrake) transcode starts... I find this...

[01:15:11] job configuration:
[01:15:11]  * source
[01:15:11]    + /home/arm/media/raw/Darkest Hour/title_**t00**.mkv
[01:15:11]    + title 1, chapter(s) 1 to 20
[01:15:11]    + container: matroska,webm
[01:15:11]    + data rate: 7873 kbps
[01:15:11]  * destination
[01:15:11]    + /home/arm/media/transcode/movies/Darkest Hour (2017)/title_t00.mkv
[01:15:11]    + container: Matroska (libavformat)
[01:15:11]      + align initial A/V stream timestamps
[01:15:11]      + chapter markers

So... it looks like a 'counter' is getting messed up somewhere.

Here is the DARKEST_HOUR.log, as well as a couple others that resulted in the same = NO movie produced... :-(

[DARKEST_HOUR.log](https://github.com/1337-server/automatic-ripping-machine/files/8239447/DARKEST_HOUR.log)
[MALEFICENT_MISTRESS_OF_EVIL.log](https://github.com/1337-server/automatic-ripping-machine/files/8239448/MALEFICENT_MISTRESS_OF_EVIL.log)
[SENNA.log](https://github.com/1337-server/automatic-ripping-machine/files/8239449/SENNA.log)

**Comment by mg-man** [comment]
Ugg... three more DVDs with the same issue today... 

[VICTORIA_AND_ABDUL.log](https://github.com/1337-server/automatic-ripping-machine/files/8240690/VICTORIA_AND_ABDUL.log)
[YESTERDAY.log](https://github.com/1337-server/automatic-ripping-machine/files/8240691/YESTERDAY.log)

[OPTD2752.log](https://github.com/1337-server/automatic-ripping-machine/files/8240689/OPTD2752.log)

**Comment by 1337-server** [comment]
It looks like the code for finding the main feature isn't working correctly.

Confirmed this bug still exists.

**Comment by 1337-server** [comment]
Latest commit might fix this. If you wouldn't mind trying it out and letting me know, that would be great.

Thanks

**Comment by mg-man** [comment]
I'll be happy to try the latest updates if it will help?  I'm working off the Ubuntu18 Branch, so are these updates also there?  

And... (as mentioned elsewhere, GitHub noob here) what is the correct way to pull the latest (Branch) updates and do I need to backup anything before like arm.yaml?  

Thanks!

**Comment by 1337-server** [comment]
I haven't had time to update the Ubuntu 18 branch yet, and i most likely won't until it's fully tested. It would create a lot of extra work, and I already have limited amount of time to work on it. 

Sorry. 

But once it's tested, and I know it's working on Ubuntu 20 and Debian, ill port the changes over.

**Comment by mg-man** [comment]
No problem at all!  I'm happy to help/test, but as previously mentioned... after being out of acti9n for ~2 yrs, I'm sticking with 18.04 until I can get through the rest of my CD ripping.  Thanks to you and **wolfy** for all the work to get A.R.M. going again!

**Comment by 1337-server** [comment]
No worries, I totally understand. When I first got A.R.M working, I had hundreds of DVD's and a few dozen CD's. I just wanted it to work, so I know where you're coming from.
